### ISSUE TITLE
Can't make it work with WSGI and apache2

### ISSUE THREAD

**Issue by chitopunk** [gerold-penz/python-jsonrpc#34]
I've added the script alias within apache config:

WSGIScriptAlias /jsonrpc /usr/local/pdit/bin/cherry.py

the script is being executed correctly but I get 404 error

from apache error_log

[Tue Aug 18 21:51:32 2015] [error] 18.7.9.7 - - [18/Aug/2015:21:51:32] "POST /jsonrpc HTTP/1.1" 404 1265 "" "Python-urllib/2.7"

And from the client:

urllib2.HTTPError: HTTP Error 404: Not Found

With a GET method thru a web browser..

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/CherryPy-3.8.0-py2.6.egg/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.6/site-packages/CherryPy-3.8.0-py2.6.egg/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/CherryPy-3.8.0-py2.6.egg/cherrypy/_cperror.py", line 411, in __call__
    raise self
NotFound: (404, "The path '/jsonrpc/' was not found.")

**Comment by gerold-penz** [comment]
I hope, you have resolved it yourself. You need a request-handler inside your Python application for "/jsonrpc".
